server:
  port: 1194

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_blog?&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  web:
    resources:
      static-locations: classpath:/static/,file:static/

  #  前端freemarker配置
  # 配置freemark的相关的信息
  freemarker:
    # 后缀
    suffix: .ftl
    content-type: text/html
    charset: utf-8
    cache: true

  #redis配置
  redis:
    host: localhost # Redis 主机地址
    port: 6379 # Redis 端口，默认是6379
    #password: yourpassword # 如果你的 Redis 设置了密码，在这里填写
    database: 0 # 默认数据库索引
    timeout: 10000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 10 # 连接池最大连接数
        max-wait: -1 # 连接池最大等待时间（毫秒）
        max-idle: 5 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数

#阿里云相关配置
#用于Windows和linux中盘符切换
file.separator: \
#阿里云OSS
aliyun:
  oss:
    #地域--越近访问越快
    endpoint: "oss-cn-guangzhou.aliyuncs.com"
    #阿里云主账号AccessKey拥有所有API的访问权限
    accessKeyId: "LTAI5t6w3aKPb7fSzbCac6sE"
    accessKeySecret: "s0CuzihItV8Ye5EiPCyZIqasSaXtcM"
    #存储空间
    bucketName: "cjr-sport-system"
    #阿里云访问目录(oss中的文件夹名称)
    rootPath: "cbyblog/"


mybatis-plus:
  type-aliases-package: com.xiaoyang.pojo
  configuration:
    call-setters-on-nulls: false
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    field-strategy: 0
    banner: true
    db-config:
      id-type: uuid
      logic-not-delete-value: 1
      logic-delete-value: 0
logging:
  level:
    root: info


